/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertasRouteImport } from './routes/app.alertas'
import { Route as AppAnomaliasRouteImport } from './routes/app.anomalias'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppEstacoesRouteImport } from './routes/app.estacoes'
import { Route as AppGrafanaRouteImport } from './routes/app.grafana'
import { Route as AppMonitoramentoRouteImport } from './routes/app.monitoramento'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppSensoresRouteImport } from './routes/app.sensores'
import { Route as AppUtilizadoresRouteImport } from './routes/app.utilizadores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliasRoute = AppAnomaliasRouteImport.update({
  id: '/anomalias',
  path: '/anomalias',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstacoesRoute = AppEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppGrafanaRoute = AppGrafanaRouteImport.update({
  id: '/grafana',
  path: '/grafana',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoramentoRoute = AppMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppSensoresRoute = AppSensoresRouteImport.update({
  id: '/sensores',
  path: '/sensores',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilizadoresRoute = AppUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registo': typeof RegistoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sobre': typeof SobreRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/anomalias': typeof AppAnomaliasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/grafana': typeof AppGrafanaRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sensores': typeof AppSensoresRoute
  '/app/utilizadores': typeof AppUtilizadoresRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registo': typeof RegistoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sobre': typeof SobreRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/anomalias': typeof AppAnomaliasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/grafana': typeof AppGrafanaRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sensores': typeof AppSensoresRoute
  '/app/utilizadores': typeof AppUtilizadoresRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registo': typeof RegistoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sobre': typeof SobreRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/anomalias': typeof AppAnomaliasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/grafana': typeof AppGrafanaRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/sensores': typeof AppSensoresRoute
  '/app/utilizadores': typeof AppUtilizadoresRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/registo'
    | '/relatorios'
    | '/sobre'
    | '/app/alertas'
    | '/app/anomalias'
    | '/app/configuracoes'
    | '/app/estacoes'
    | '/app/grafana'
    | '/app/monitoramento'
    | '/app/perfil'
    | '/app/sensores'
    | '/app/utilizadores'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/registo'
    | '/relatorios'
    | '/sobre'
    | '/app/alertas'
    | '/app/anomalias'
    | '/app/configuracoes'
    | '/app/estacoes'
    | '/app/grafana'
    | '/app/monitoramento'
    | '/app/perfil'
    | '/app/sensores'
    | '/app/utilizadores'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/registo'
    | '/relatorios'
    | '/sobre'
    | '/app/alertas'
    | '/app/anomalias'
    | '/app/configuracoes'
    | '/app/estacoes'
    | '/app/grafana'
    | '/app/monitoramento'
    | '/app/perfil'
    | '/app/sensores'
    | '/app/utilizadores'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegistoRoute: typeof RegistoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anomalias': {
      id: '/app/anomalias'
      path: '/anomalias'
      fullPath: '/app/anomalias'
      preLoaderRoute: typeof AppAnomaliasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estacoes': {
      id: '/app/estacoes'
      path: '/estacoes'
      fullPath: '/app/estacoes'
      preLoaderRoute: typeof AppEstacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grafana': {
      id: '/app/grafana'
      path: '/grafana'
      fullPath: '/app/grafana'
      preLoaderRoute: typeof AppGrafanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoramento': {
      id: '/app/monitoramento'
      path: '/monitoramento'
      fullPath: '/app/monitoramento'
      preLoaderRoute: typeof AppMonitoramentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sensores': {
      id: '/app/sensores'
      path: '/sensores'
      fullPath: '/app/sensores'
      preLoaderRoute: typeof AppSensoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/utilizadores': {
      id: '/app/utilizadores'
      path: '/utilizadores'
      fullPath: '/app/utilizadores'
      preLoaderRoute: typeof AppUtilizadoresRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppAnomaliasRoute: typeof AppAnomaliasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstacoesRoute: typeof AppEstacoesRoute
  AppGrafanaRoute: typeof AppGrafanaRoute
  AppMonitoramentoRoute: typeof AppMonitoramentoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSensoresRoute: typeof AppSensoresRoute
  AppUtilizadoresRoute: typeof AppUtilizadoresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppAnomaliasRoute: AppAnomaliasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstacoesRoute: AppEstacoesRoute,
  AppGrafanaRoute: AppGrafanaRoute,
  AppMonitoramentoRoute: AppMonitoramentoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSensoresRoute: AppSensoresRoute,
  AppUtilizadoresRoute: AppUtilizadoresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegistoRoute: RegistoRoute,
  RelatoriosRoute: RelatoriosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
